language: node_js
node_js:
  - "7"
env:
  - CXX=g++-6
script:
  - npm run lint
  - npm test
cache: yarn
services:
  - mongodb
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
